//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sfw.Sabp.Mca.DataAccess.Ef
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Sfw.Sabp.Mca.Model;
    
    public partial class Mca : DbContext
    {
        public Mca()
            : base("name=Mca")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Option> Options { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<WorkflowQuestion> WorkflowQuestions { get; set; }
        public virtual DbSet<WorkflowStep> WorkflowSteps { get; set; }
        public virtual DbSet<WorkflowVersion> WorkflowVersions { get; set; }
        public virtual DbSet<QuestionOption> QuestionOptions { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Assessment> Assessments { get; set; }
        public virtual DbSet<AuditLog> AuditLogs { get; set; }
        public virtual DbSet<WorkflowStage> WorkflowStages { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<Disclaimer> Disclaimers { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<QuestionAnswer> QuestionAnswers { get; set; }
    }
}
