// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.34209
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Sfw.Sabp.Mca.Specflow.Tests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class Stage3Feature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Stage3.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Stage3", "", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "Stage3")))
            {
                Sfw.Sabp.Mca.Specflow.Tests.Stage3Feature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void AnswerQuestion(string question, string option, string nextquestion, string outcome, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "mytag"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Answer question", @__tags);
#line 4
this.ScenarioSetup(scenarioInfo);
#line 5
 testRunner.Given(string.Format("I have answered {0} with {1}", question, option), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 6
 testRunner.Then(string.Format("the next question should be {0}", nextquestion), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 7
 testRunner.And(string.Format("the next question outcome should be {0}", outcome), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Answer question")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Stage3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:question", "4394AE4B-937C-487C-8A90-B36308BDC291")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:option", "84E3D60D-4846-4DB2-8A37-D37FC4629F1C")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:nextquestion", "1ADDE9A4-5D3A-40E8-8837-D46E9B23A77A")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:outcome", "1")]
        public virtual void AnswerQuestion_Variant0()
        {
            this.AnswerQuestion("4394AE4B-937C-487C-8A90-B36308BDC291", "84E3D60D-4846-4DB2-8A37-D37FC4629F1C", "1ADDE9A4-5D3A-40E8-8837-D46E9B23A77A", "1", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Answer question")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Stage3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:question", "1ADDE9A4-5D3A-40E8-8837-D46E9B23A77A")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:option", "F47EC38E-0798-450D-B139-7FA68F936B27")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:nextquestion", "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:outcome", "3")]
        public virtual void AnswerQuestion_Variant1()
        {
            this.AnswerQuestion("1ADDE9A4-5D3A-40E8-8837-D46E9B23A77A", "F47EC38E-0798-450D-B139-7FA68F936B27", "", "3", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Answer question")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Stage3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:question", "4394AE4B-937C-487C-8A90-B36308BDC291")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:option", "96991A39-5406-4961-810A-825DA5734198")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:nextquestion", "9D57237B-E46C-4C6B-8DD0-7EB3D114EC0C")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:outcome", "1")]
        public virtual void AnswerQuestion_Variant2()
        {
            this.AnswerQuestion("4394AE4B-937C-487C-8A90-B36308BDC291", "96991A39-5406-4961-810A-825DA5734198", "9D57237B-E46C-4C6B-8DD0-7EB3D114EC0C", "1", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Answer question")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Stage3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:question", "9D57237B-E46C-4C6B-8DD0-7EB3D114EC0C")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:option", "76051066-44D8-48CD-B835-3F8D388F1F17")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:nextquestion", "8A566C66-3361-4492-8F5C-A2C54A60EADC")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:outcome", "1")]
        public virtual void AnswerQuestion_Variant3()
        {
            this.AnswerQuestion("9D57237B-E46C-4C6B-8DD0-7EB3D114EC0C", "76051066-44D8-48CD-B835-3F8D388F1F17", "8A566C66-3361-4492-8F5C-A2C54A60EADC", "1", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Answer question")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Stage3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 4")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:question", "9D57237B-E46C-4C6B-8DD0-7EB3D114EC0C")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:option", "A42245EC-6F9E-4448-A8AA-C15DC27E1E3E")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:nextquestion", "D38097A8-5A96-43DA-A904-29A917CA6688")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:outcome", "1")]
        public virtual void AnswerQuestion_Variant4()
        {
            this.AnswerQuestion("9D57237B-E46C-4C6B-8DD0-7EB3D114EC0C", "A42245EC-6F9E-4448-A8AA-C15DC27E1E3E", "D38097A8-5A96-43DA-A904-29A917CA6688", "1", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Answer question")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Stage3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:question", "8A566C66-3361-4492-8F5C-A2C54A60EADC")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:option", "7BDE5229-631A-4EFF-A73E-948A088E1E8F")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:nextquestion", "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:outcome", "3")]
        public virtual void AnswerQuestion_Variant5()
        {
            this.AnswerQuestion("8A566C66-3361-4492-8F5C-A2C54A60EADC", "7BDE5229-631A-4EFF-A73E-948A088E1E8F", "", "3", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Answer question")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Stage3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 6")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:question", "8A566C66-3361-4492-8F5C-A2C54A60EADC")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:option", "D89638FB-1CD5-498D-9179-91C349C6A753")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:nextquestion", "D38097A8-5A96-43DA-A904-29A917CA6688")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:outcome", "1")]
        public virtual void AnswerQuestion_Variant6()
        {
            this.AnswerQuestion("8A566C66-3361-4492-8F5C-A2C54A60EADC", "D89638FB-1CD5-498D-9179-91C349C6A753", "D38097A8-5A96-43DA-A904-29A917CA6688", "1", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Answer question")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Stage3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 7")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:question", "D38097A8-5A96-43DA-A904-29A917CA6688")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:option", "69D09F2B-80F1-4960-A9E7-952402FBCB02")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:nextquestion", "7F81BC82-E5CE-468F-B765-0E8417EC97CD")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:outcome", "1")]
        public virtual void AnswerQuestion_Variant7()
        {
            this.AnswerQuestion("D38097A8-5A96-43DA-A904-29A917CA6688", "69D09F2B-80F1-4960-A9E7-952402FBCB02", "7F81BC82-E5CE-468F-B765-0E8417EC97CD", "1", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Answer question")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Stage3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 8")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:question", "D38097A8-5A96-43DA-A904-29A917CA6688")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:option", "88DDAEC7-9A78-479B-A5A3-DD15378EDC47")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:nextquestion", "382AD014-DF18-4BEF-ABBD-F00730EE92F7")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:outcome", "1")]
        public virtual void AnswerQuestion_Variant8()
        {
            this.AnswerQuestion("D38097A8-5A96-43DA-A904-29A917CA6688", "88DDAEC7-9A78-479B-A5A3-DD15378EDC47", "382AD014-DF18-4BEF-ABBD-F00730EE92F7", "1", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Answer question")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Stage3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 9")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:question", "382AD014-DF18-4BEF-ABBD-F00730EE92F7")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:option", "7BDE5229-631A-4EFF-A73E-948A088E1E8F")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:nextquestion", "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:outcome", "3")]
        public virtual void AnswerQuestion_Variant9()
        {
            this.AnswerQuestion("382AD014-DF18-4BEF-ABBD-F00730EE92F7", "7BDE5229-631A-4EFF-A73E-948A088E1E8F", "", "3", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Answer question")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Stage3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 10")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:question", "382AD014-DF18-4BEF-ABBD-F00730EE92F7")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:option", "D89638FB-1CD5-498D-9179-91C349C6A753")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:nextquestion", "7F81BC82-E5CE-468F-B765-0E8417EC97CD")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:outcome", "1")]
        public virtual void AnswerQuestion_Variant10()
        {
            this.AnswerQuestion("382AD014-DF18-4BEF-ABBD-F00730EE92F7", "D89638FB-1CD5-498D-9179-91C349C6A753", "7F81BC82-E5CE-468F-B765-0E8417EC97CD", "1", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Answer question")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Stage3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 11")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:question", "7F81BC82-E5CE-468F-B765-0E8417EC97CD")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:option", "8A1AA021-8842-4783-A09C-A93B6C595141")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:nextquestion", "F871A5C0-B5AC-4A8F-8A85-5F3658DFEC57")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:outcome", "1")]
        public virtual void AnswerQuestion_Variant11()
        {
            this.AnswerQuestion("7F81BC82-E5CE-468F-B765-0E8417EC97CD", "8A1AA021-8842-4783-A09C-A93B6C595141", "F871A5C0-B5AC-4A8F-8A85-5F3658DFEC57", "1", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Answer question")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Stage3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 12")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:question", "7F81BC82-E5CE-468F-B765-0E8417EC97CD")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:option", "1BE2AEC8-1706-448E-A988-7779F9B70D1F")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:nextquestion", "F1C3D7A6-B164-41A0-AFD3-5AB54F9C3D91")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:outcome", "1")]
        public virtual void AnswerQuestion_Variant12()
        {
            this.AnswerQuestion("7F81BC82-E5CE-468F-B765-0E8417EC97CD", "1BE2AEC8-1706-448E-A988-7779F9B70D1F", "F1C3D7A6-B164-41A0-AFD3-5AB54F9C3D91", "1", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Answer question")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Stage3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 13")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:question", "F871A5C0-B5AC-4A8F-8A85-5F3658DFEC57")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:option", "7BDE5229-631A-4EFF-A73E-948A088E1E8F")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:nextquestion", "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:outcome", "3")]
        public virtual void AnswerQuestion_Variant13()
        {
            this.AnswerQuestion("F871A5C0-B5AC-4A8F-8A85-5F3658DFEC57", "7BDE5229-631A-4EFF-A73E-948A088E1E8F", "", "3", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Answer question")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Stage3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 14")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:question", "F871A5C0-B5AC-4A8F-8A85-5F3658DFEC57")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:option", "D89638FB-1CD5-498D-9179-91C349C6A753")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:nextquestion", "F1C3D7A6-B164-41A0-AFD3-5AB54F9C3D91")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:outcome", "1")]
        public virtual void AnswerQuestion_Variant14()
        {
            this.AnswerQuestion("F871A5C0-B5AC-4A8F-8A85-5F3658DFEC57", "D89638FB-1CD5-498D-9179-91C349C6A753", "F1C3D7A6-B164-41A0-AFD3-5AB54F9C3D91", "1", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Answer question")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Stage3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 15")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:question", "F1C3D7A6-B164-41A0-AFD3-5AB54F9C3D91")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:option", "5CB217BD-78DD-41D5-9B40-A708A69F5F21")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:nextquestion", "7391B87F-D05A-4A01-97AD-C05DC3F2477E")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:outcome", "1")]
        public virtual void AnswerQuestion_Variant15()
        {
            this.AnswerQuestion("F1C3D7A6-B164-41A0-AFD3-5AB54F9C3D91", "5CB217BD-78DD-41D5-9B40-A708A69F5F21", "7391B87F-D05A-4A01-97AD-C05DC3F2477E", "1", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Answer question")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Stage3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 16")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:question", "F1C3D7A6-B164-41A0-AFD3-5AB54F9C3D91")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:option", "D5395000-2351-4694-BD7D-71DD7CA91E69")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:nextquestion", "A59530F6-2C6E-4F75-A691-0FC750112AD4")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:outcome", "1")]
        public virtual void AnswerQuestion_Variant16()
        {
            this.AnswerQuestion("F1C3D7A6-B164-41A0-AFD3-5AB54F9C3D91", "D5395000-2351-4694-BD7D-71DD7CA91E69", "A59530F6-2C6E-4F75-A691-0FC750112AD4", "1", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Answer question")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Stage3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 17")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:question", "A59530F6-2C6E-4F75-A691-0FC750112AD4")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:option", "DD0B6F95-2E80-4872-8641-04E59549CC57")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:nextquestion", "84D89B55-349C-4B7A-85C0-5035CFFA7492")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:outcome", "1")]
        public virtual void AnswerQuestion_Variant17()
        {
            this.AnswerQuestion("A59530F6-2C6E-4F75-A691-0FC750112AD4", "DD0B6F95-2E80-4872-8641-04E59549CC57", "84D89B55-349C-4B7A-85C0-5035CFFA7492", "1", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Answer question")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Stage3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 18")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:question", "7391B87F-D05A-4A01-97AD-C05DC3F2477E")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:option", "7BDE5229-631A-4EFF-A73E-948A088E1E8F")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:nextquestion", "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:outcome", "3")]
        public virtual void AnswerQuestion_Variant18()
        {
            this.AnswerQuestion("7391B87F-D05A-4A01-97AD-C05DC3F2477E", "7BDE5229-631A-4EFF-A73E-948A088E1E8F", "", "3", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Answer question")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Stage3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 19")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:question", "7391B87F-D05A-4A01-97AD-C05DC3F2477E")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:option", "D89638FB-1CD5-498D-9179-91C349C6A753")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:nextquestion", "A59530F6-2C6E-4F75-A691-0FC750112AD4")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:outcome", "1")]
        public virtual void AnswerQuestion_Variant19()
        {
            this.AnswerQuestion("7391B87F-D05A-4A01-97AD-C05DC3F2477E", "D89638FB-1CD5-498D-9179-91C349C6A753", "A59530F6-2C6E-4F75-A691-0FC750112AD4", "1", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Answer question")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Stage3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 20")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:question", "84D89B55-349C-4B7A-85C0-5035CFFA7492")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:option", "65A4E159-E782-4BD8-BE01-30FFDF516C81")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:nextquestion", "B7F7302C-A92A-4818-AA32-6A01D2AC14AD")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:outcome", "1")]
        public virtual void AnswerQuestion_Variant20()
        {
            this.AnswerQuestion("84D89B55-349C-4B7A-85C0-5035CFFA7492", "65A4E159-E782-4BD8-BE01-30FFDF516C81", "B7F7302C-A92A-4818-AA32-6A01D2AC14AD", "1", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Answer question")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Stage3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 21")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:question", "84D89B55-349C-4B7A-85C0-5035CFFA7492")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:option", "326B34E9-692E-4363-84C1-3B8871B1F042")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:nextquestion", "7D765696-05AA-4E35-9EBC-24D4EA98FF04")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:outcome", "1")]
        public virtual void AnswerQuestion_Variant21()
        {
            this.AnswerQuestion("84D89B55-349C-4B7A-85C0-5035CFFA7492", "326B34E9-692E-4363-84C1-3B8871B1F042", "7D765696-05AA-4E35-9EBC-24D4EA98FF04", "1", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Answer question")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Stage3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 22")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:question", "B7F7302C-A92A-4818-AA32-6A01D2AC14AD")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:option", "05A04BAD-7B59-43F5-86DF-3F3A00E9B14C")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:nextquestion", "7D765696-05AA-4E35-9EBC-24D4EA98FF04")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:outcome", "1")]
        public virtual void AnswerQuestion_Variant22()
        {
            this.AnswerQuestion("B7F7302C-A92A-4818-AA32-6A01D2AC14AD", "05A04BAD-7B59-43F5-86DF-3F3A00E9B14C", "7D765696-05AA-4E35-9EBC-24D4EA98FF04", "1", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Answer question")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Stage3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 23")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:question", "B7F7302C-A92A-4818-AA32-6A01D2AC14AD")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:option", "F2335E13-3D15-436F-8C86-BE8DB6EFC4DA")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:nextquestion", "A617FAAF-09EE-42F1-BB87-1995BA3444F1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:outcome", "1")]
        public virtual void AnswerQuestion_Variant23()
        {
            this.AnswerQuestion("B7F7302C-A92A-4818-AA32-6A01D2AC14AD", "F2335E13-3D15-436F-8C86-BE8DB6EFC4DA", "A617FAAF-09EE-42F1-BB87-1995BA3444F1", "1", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Answer question")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Stage3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 24")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:question", "A617FAAF-09EE-42F1-BB87-1995BA3444F1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:option", "7BDE5229-631A-4EFF-A73E-948A088E1E8F")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:nextquestion", "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:outcome", "3")]
        public virtual void AnswerQuestion_Variant24()
        {
            this.AnswerQuestion("A617FAAF-09EE-42F1-BB87-1995BA3444F1", "7BDE5229-631A-4EFF-A73E-948A088E1E8F", "", "3", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Answer question")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Stage3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 25")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:question", "A617FAAF-09EE-42F1-BB87-1995BA3444F1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:option", "D89638FB-1CD5-498D-9179-91C349C6A753")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:nextquestion", "7D765696-05AA-4E35-9EBC-24D4EA98FF04")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:outcome", "1")]
        public virtual void AnswerQuestion_Variant25()
        {
            this.AnswerQuestion("A617FAAF-09EE-42F1-BB87-1995BA3444F1", "D89638FB-1CD5-498D-9179-91C349C6A753", "7D765696-05AA-4E35-9EBC-24D4EA98FF04", "1", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Answer question")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Stage3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 26")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:question", "7D765696-05AA-4E35-9EBC-24D4EA98FF04")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:option", "5EB4577C-20D2-4BD2-B798-5E9DF600FA91")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:nextquestion", "963CB31F-6EC0-4184-8C29-41E66F3F4D37")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:outcome", "1")]
        public virtual void AnswerQuestion_Variant26()
        {
            this.AnswerQuestion("7D765696-05AA-4E35-9EBC-24D4EA98FF04", "5EB4577C-20D2-4BD2-B798-5E9DF600FA91", "963CB31F-6EC0-4184-8C29-41E66F3F4D37", "1", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Answer question")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Stage3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 27")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:question", "7D765696-05AA-4E35-9EBC-24D4EA98FF04")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:option", "4B753CC9-7124-4110-AA93-CF6E884074D0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:nextquestion", "4538B455-9FB9-4C84-AA20-4663FA2750F0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:outcome", "1")]
        public virtual void AnswerQuestion_Variant27()
        {
            this.AnswerQuestion("7D765696-05AA-4E35-9EBC-24D4EA98FF04", "4B753CC9-7124-4110-AA93-CF6E884074D0", "4538B455-9FB9-4C84-AA20-4663FA2750F0", "1", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Answer question")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Stage3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 28")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:question", "963CB31F-6EC0-4184-8C29-41E66F3F4D37")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:option", "804F31BD-DFEA-48A1-A550-A7E7542B0C78")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:nextquestion", "4538B455-9FB9-4C84-AA20-4663FA2750F0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:outcome", "1")]
        public virtual void AnswerQuestion_Variant28()
        {
            this.AnswerQuestion("963CB31F-6EC0-4184-8C29-41E66F3F4D37", "804F31BD-DFEA-48A1-A550-A7E7542B0C78", "4538B455-9FB9-4C84-AA20-4663FA2750F0", "1", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Answer question")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Stage3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 29")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:question", "963CB31F-6EC0-4184-8C29-41E66F3F4D37")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:option", "2FDC336D-0A77-4E10-834F-0F2F923CA79C")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:nextquestion", "D9DF7F32-ABD7-4BF5-9A99-EA29B6CCF03A")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:outcome", "1")]
        public virtual void AnswerQuestion_Variant29()
        {
            this.AnswerQuestion("963CB31F-6EC0-4184-8C29-41E66F3F4D37", "2FDC336D-0A77-4E10-834F-0F2F923CA79C", "D9DF7F32-ABD7-4BF5-9A99-EA29B6CCF03A", "1", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Answer question")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Stage3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 30")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:question", "D9DF7F32-ABD7-4BF5-9A99-EA29B6CCF03A")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:option", "7BDE5229-631A-4EFF-A73E-948A088E1E8F")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:nextquestion", "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:outcome", "3")]
        public virtual void AnswerQuestion_Variant30()
        {
            this.AnswerQuestion("D9DF7F32-ABD7-4BF5-9A99-EA29B6CCF03A", "7BDE5229-631A-4EFF-A73E-948A088E1E8F", "", "3", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Answer question")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Stage3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 31")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:question", "D9DF7F32-ABD7-4BF5-9A99-EA29B6CCF03A")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:option", "D89638FB-1CD5-498D-9179-91C349C6A753")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:nextquestion", "4538B455-9FB9-4C84-AA20-4663FA2750F0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:outcome", "1")]
        public virtual void AnswerQuestion_Variant31()
        {
            this.AnswerQuestion("D9DF7F32-ABD7-4BF5-9A99-EA29B6CCF03A", "D89638FB-1CD5-498D-9179-91C349C6A753", "4538B455-9FB9-4C84-AA20-4663FA2750F0", "1", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Answer question")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Stage3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 32")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:question", "4538B455-9FB9-4C84-AA20-4663FA2750F0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:option", "B86D2A99-C34D-4420-B7F4-9E7873D6C305")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:nextquestion", "D3FCB9CF-584A-4C07-84E5-62059FDD2093")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:outcome", "1")]
        public virtual void AnswerQuestion_Variant32()
        {
            this.AnswerQuestion("4538B455-9FB9-4C84-AA20-4663FA2750F0", "B86D2A99-C34D-4420-B7F4-9E7873D6C305", "D3FCB9CF-584A-4C07-84E5-62059FDD2093", "1", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Answer question")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Stage3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 33")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:question", "4538B455-9FB9-4C84-AA20-4663FA2750F0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:option", "F7CA0816-B4D5-418D-BF6E-710CA5B829BF")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:nextquestion", "17D7C17A-3665-4DFC-B54E-B4851D10C70D")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:outcome", "1")]
        public virtual void AnswerQuestion_Variant33()
        {
            this.AnswerQuestion("4538B455-9FB9-4C84-AA20-4663FA2750F0", "F7CA0816-B4D5-418D-BF6E-710CA5B829BF", "17D7C17A-3665-4DFC-B54E-B4851D10C70D", "1", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Answer question")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Stage3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 34")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:question", "D3FCB9CF-584A-4C07-84E5-62059FDD2093")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:option", "01731380-FC2F-45D6-96ED-3EC6A83326BF")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:nextquestion", "17D7C17A-3665-4DFC-B54E-B4851D10C70D")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:outcome", "1")]
        public virtual void AnswerQuestion_Variant34()
        {
            this.AnswerQuestion("D3FCB9CF-584A-4C07-84E5-62059FDD2093", "01731380-FC2F-45D6-96ED-3EC6A83326BF", "17D7C17A-3665-4DFC-B54E-B4851D10C70D", "1", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Answer question")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Stage3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 35")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:question", "D3FCB9CF-584A-4C07-84E5-62059FDD2093")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:option", "CE82417C-6CD9-47D5-8E9E-FE86372D8AF7")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:nextquestion", "E522D7CE-CBD0-4490-83F1-C32EEC7B6D6A")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:outcome", "1")]
        public virtual void AnswerQuestion_Variant35()
        {
            this.AnswerQuestion("D3FCB9CF-584A-4C07-84E5-62059FDD2093", "CE82417C-6CD9-47D5-8E9E-FE86372D8AF7", "E522D7CE-CBD0-4490-83F1-C32EEC7B6D6A", "1", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Answer question")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Stage3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 36")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:question", "E522D7CE-CBD0-4490-83F1-C32EEC7B6D6A")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:option", "7BDE5229-631A-4EFF-A73E-948A088E1E8F")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:nextquestion", "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:outcome", "3")]
        public virtual void AnswerQuestion_Variant36()
        {
            this.AnswerQuestion("E522D7CE-CBD0-4490-83F1-C32EEC7B6D6A", "7BDE5229-631A-4EFF-A73E-948A088E1E8F", "", "3", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Answer question")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Stage3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 37")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:question", "E522D7CE-CBD0-4490-83F1-C32EEC7B6D6A")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:option", "D89638FB-1CD5-498D-9179-91C349C6A753")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:nextquestion", "17D7C17A-3665-4DFC-B54E-B4851D10C70D")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:outcome", "1")]
        public virtual void AnswerQuestion_Variant37()
        {
            this.AnswerQuestion("E522D7CE-CBD0-4490-83F1-C32EEC7B6D6A", "D89638FB-1CD5-498D-9179-91C349C6A753", "17D7C17A-3665-4DFC-B54E-B4851D10C70D", "1", ((string[])(null)));
        }
    }
}
#pragma warning restore
#endregion
