//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sfw.Sabp.Mca.Model
{
    using Sfw.Sabp.Mca.Core.Contracts;
    using System;
    using System.Collections.Generic;
    
    
    
    public partial class Assessment  : IQueryResult
    {
        public Assessment()
        {
            this.QuestionAnswers = new HashSet<QuestionAnswer>();
        }
    
        public System.Guid AssessmentId { get; set; }
        public System.Guid PatientId { get; set; }
        public Nullable<System.DateTime> DateAssessmentStarted { get; set; }
        public string Stage1InfoText { get; set; }
        public string Stage1DecisionToBeMade { get; set; }
        public string Stage1DecisionConfirmation { get; set; }
        public bool Stage1DecisionClearlyMade { get; set; }
        public System.Guid CurrentWorkflowQuestionId { get; set; }
        public System.Guid WorkflowVersionId { get; set; }
        public string AssessorName { get; set; }
        public int StatusId { get; set; }
        public Nullable<System.Guid> PreviousWorkflowQuestionId { get; set; }
        public string AssessorDomainName { get; set; }
        public bool ReadOnly { get; set; }
        public Nullable<System.Guid> ResetWorkflowQuestionId { get; set; }
        public Nullable<System.DateTime> DateAssessmentEnded { get; set; }
        public string TerminatedAssessmentReason { get; set; }
        public int RoleId { get; set; }
        public string DecisionMaker { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual WorkflowQuestion WorkflowQuestion { get; set; }
        public virtual WorkflowVersion WorkflowVersion { get; set; }
        public virtual WorkflowQuestion PreviousWorkflowQuestion { get; set; }
        public virtual WorkflowQuestion ResetWorkflowQuestion { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<QuestionAnswer> QuestionAnswers { get; set; }
    }
}
