//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sfw.Sabp.Mca.Model
{
    using Sfw.Sabp.Mca.Core.Contracts;
    using System;
    using System.Collections.Generic;
    
    
    
    public partial class AuditLog  : IQueryResult
    {
        public System.Guid AuditLogId { get; set; }
        public string User { get; set; }
        public System.DateTime EventDateTime { get; set; }
        public string Action { get; set; }
        public string Controller { get; set; }
        public string AuditData { get; set; }
    }
}
