//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sfw.Sabp.Mca.Model
{
    using Sfw.Sabp.Mca.Core.Contracts;
    using System;
    using System.Collections.Generic;
    
    
    
    public partial class QuestionAnswer  : IQueryResult
    {
        public System.Guid QuestionAnswerId { get; set; }
        public System.Guid AssessmentId { get; set; }
        public System.Guid WorkflowQuestionId { get; set; }
        public System.Guid QuestionOptionId { get; set; }
        public string FurtherInformation { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual Assessment Assessment { get; set; }
        public virtual QuestionOption QuestionOption { get; set; }
        public virtual WorkflowQuestion WorkflowQuestion { get; set; }
    }
}
