//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sfw.Sabp.Mca.Model
{
    using Sfw.Sabp.Mca.Core.Contracts;
    using System;
    using System.Collections.Generic;
    
    
    
    public partial class QuestionOption  : IQueryResult
    {
        public QuestionOption()
        {
            this.WorkflowSteps = new HashSet<WorkflowStep>();
            this.QuestionAnswers = new HashSet<QuestionAnswer>();
        }
    
        public System.Guid QuestionOptionId { get; set; }
        public System.Guid QuestionId { get; set; }
        public System.Guid OptionId { get; set; }
        public Nullable<System.Guid> FurtherInformationQuestionId { get; set; }
        public int Order { get; set; }
    
        public virtual Option Option { get; set; }
        public virtual Question FurtherQuestion { get; set; }
        public virtual Question Question { get; set; }
        public virtual ICollection<WorkflowStep> WorkflowSteps { get; set; }
        public virtual ICollection<QuestionAnswer> QuestionAnswers { get; set; }
    }
}
