//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sfw.Sabp.Mca.Model
{
    using Sfw.Sabp.Mca.Core.Contracts;
    using System;
    using System.Collections.Generic;
    
    
    
    public partial class WorkflowVersion  : IQueryResult
    {
        public WorkflowVersion()
        {
            this.WorkflowSteps = new HashSet<WorkflowStep>();
            this.Assessments = new HashSet<Assessment>();
            this.WorkflowStages = new HashSet<WorkflowStage>();
        }
    
        public System.Guid WorkflowVersionId { get; set; }
        public string Description { get; set; }
        public System.Guid InitialWorkflowQuestionId { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
    
        public virtual WorkflowQuestion WorkflowQuestion { get; set; }
        public virtual ICollection<WorkflowStep> WorkflowSteps { get; set; }
        public virtual ICollection<Assessment> Assessments { get; set; }
        public virtual ICollection<WorkflowStage> WorkflowStages { get; set; }
    }
}
